gnirps:
    database:
        url: jdbc:mariadb://${DATABASE_URL}/${DATABASE_NAME}?createDatabaseIfNotExist=true&useUnicode=true&character_set_server=utf8mb4
        driver-class-name: 'org.mariadb.jdbc.Driver'
        dialect: 'org.hibernate.dialect.MariaDB102Dialect'
        hibernate-additional-properties:
            -   hibernate.connection.CharSet: utf8mb4
            -   hibernate.connection.characterEncoding: utf8
            -   hibernate.connection.useUnicode: true