version: '3.7'

volumes:
    cat-volume:

services:
    database:
        image: postgres:11.1-alpine
        deploy:
            restart_policy:
                condition: on-failure
        ports:
            - 8081:5432
        environment:
            POSTGRES_DB: cat-db-name
            POSTGRES_USER: cat-db-user
            POSTGRES_PASSWORD: cat-db-password
        volumes:
            - "cat-volume:/var/lib/postgresql/data"

    api:
        image: pittinic/gnirps:cat-api-tls
        ports:
            - 8080:8080
            - 8443:8443
        environment:
            DATABASE_URL: database:5432
            DATABASE_NAME: cat-db-name
            DATABASE_USER: cat-db-user
            DATABASE_PASSWORD: cat-db-password
            LOG_LEVEL_ROOT: WARN
            LOG_LEVEL_SPRING: WARN
            LOG_LEVEL_SPRING_SECURITY: INFO
            LOG_LEVEL_GNIRPS: DEBUG
            SSL_KEYSTORE_TYPE: PKCS12
            SSL_KEYSTORE_PATH: key-store.p12
            SSL_KEYSTORE_PASSWORD: password
            SSL_TRUSTSTORE_TYPE: JKS
            SSL_TRUSTSTORE_PATH: trust-store.jks
            SSL_TRUSTSTORE_PASSWORD: password