gnirps:
    database:
        postgresql:
            url: jdbc:postgresql://${DATABASE_URL}/${DATABASE_NAME}
            username: ${DATABASE_USER}
            password: ${DATABASE_PASSWORD}
            driver-class-name: 'org.postgresql.Driver'
            default-schema: gnirps
            database-dialect: 'org.hibernate.dialect.PostgreSQLDialect'
            naming-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
            hbm2ddl-auto: update
            use-sql-comments: true

spring:
    datasource:
        hikari:
            maximum-pool-size: 9
    jpa:
        generate-ddl: true
