gnirps:
    common:
        base-package: "com.gnirps"
        service-name: "missing: gnirps.common.service-name"
        time-zone: "Europe/Paris"
    swagger:
        base-package: ${gnirps.common.base-package}
        api:
            title: "missing-property:gnirps.swagger.title"
            description: "missing-property:gnirps.swagger.description"
            version: "missing-property:gnirps.common.version"
            license: "License: MIT"
            license-url: "https://matias.ma/nsfw/"
            terms-of-service: "https://matias.ma/nsfw/"
        maintainer:
            name: "REDLab"
            email: "nicolas.pittion@redlab.io"
            website: "https://www.redlab.io/"
    mail-sender:
        debug: false
        service-name: ${gnirps.common.service-name}
        host: smtp.gmail.com
        username: gnirps.noreply@gmail.com
        password: Gnirp$n0reply
        recipients: ${gnirps.swagger.maintainer.email}
        transport:
            protocol: smtp
        smtp:
            port: 587
            auth: true
            starttls:
                enable: true
                required: true

logging:
    level:
        root: INFO
        com.gnirps: ALL
        org.springframework.web: INFO
        org.springframework.mail: WARN