gnirps:
  database:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ''
    default-schema: gnirps
    dialect: ''
    naming-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
    hbm2ddl-auto: update
    use-sql-comments: true

#spring:
#  datasource:
#    hikari:
#      maximum-pool-size: 9
#  jpa:
#    generate-ddl: true
