gnirps:
    database:
        url: jdbc:mysql://${DATABASE_URL}/${DATABASE_NAME}?createDatabaseIfNotExist=true&useUnicode=true&character_set_server=utf8mb4
        driver-class-name: 'com.mysql.cj.jdbc.Driver'
        dialect: 'org.hibernate.dialect.MySQL8Dialect'
        hibernate-additional-properties:
            - hibernate.connection.CharSet: utf8mb4
            - hibernate.connection.characterEncoding: utf8
            - hibernate.connection.useUnicode: true