version: '3.7'

volumes:
    cat-volume:

services:
    database:
        image: mysql:8.0
        restart: always
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        deploy:
            restart_policy:
                condition: on-failure
        ports:
            - 8081:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cat-db-name
            MYSQL_USER: cat-db-user
            MYSQL_PASSWORD: cat-db-password
        volumes:
            - "cat-volume:/var/lib/mysql"

    api:
        image: pittinic/gnirps:cat-api-mysql
        ports:
            - 8080:8080
        environment:
            DATABASE_URL: database:3306
            DATABASE_NAME: cat-db-name
            DATABASE_USER: cat-db-user
            DATABASE_PASSWORD: cat-db-password