version: '3.7'

volumes:
    cat-volume:

services:
    cat-database:
        image: postgres:11.1-alpine
        deploy:
            restart_policy:
                condition: on-failure
        ports:
            - 8081:5432
        environment:
            POSTGRES_DB: cat-db-name
            POSTGRES_USER: cat-db-user
            POSTGRES_PASSWORD: cat-db-password
        volumes:
            - "cat-volume:/var/lib/postgresql/data"

    cat-api:
        image: pittinic/gnirps:cat-api
        ports:
            - 8080:8080
        environment:
            DATABASE_URL: cat-database:5432
            DATABASE_NAME: cat-db-name
            DATABASE_USER: cat-db-user
            DATABASE_PASSWORD: cat-db-password
            LOG_LEVEL_ROOT: ERROR
            LOG_LEVEL_SPRING: INFO
            LOG_LEVEL_GNIRPS: DEBUG