# https://www.keycloak.org/docs/latest/securing_apps/index.html#_java_adapter_config

gnirps:
    keycloak:
        app-name: ${gnirps.swagger.api.title}
        endpoints:
            unsecure-post: ""
            unsecure-get: ""
            unsecure-put: ""
            unsecure-delete: ""
        resources: /, /error, /csrf, /swagger/**, /swagger-ui/**, /swagger-ui.html, /webjars/**, /swagger-resources/**, /configuration/**, /v3/api-docs/**

keycloak:
    auth-server-url: "missing:keycloak.auth-server-url"
    realm: "missing:keycloak.realm"
    resource: "missing:keycloak.resource"
    bearer-only: true
    cors: true
    ssl-required: ${KEYCLOAK_SSL_REQUIRED} # NONE, EXTERNAL, ALL
    principal-attribute: ${KEYCLOAK_PRINCIPAL_ATTRIBUTE:email}
    use-resource-role-mappings: true
    credentials:
        secret: "missing:keycloak.credentials.secret"
    enabled: true

logging:
    level:
        org.keycloak: ${LOG_LEVEL_KEYCLOAK:WARN}