gnirps:
    core:
        jetty:
            idle-timeout: 300000
        time-zone:
            name: "Europe/Paris"
        mail-sender:
            debug: false
            service-name: "missing-property:gnirps.core.mail-sender.service-name"
            host: smtp.gmail.com
            username: gnirps.noreply@gmail.com  # TODO remove from code
            password: Gnirp$n0reply             # TODO remove from code
            recipients:
            transport:
                protocol: smtp
            smtp:
                port: 587
                auth: true
                starttls:
                    enable: true
                    required: true
        cors:
            access-control-allow-origin: "*"
            access-control-allow-methods: "POST, PUT, GET, OPTIONS, DELETE"
            access-control-allow-headers: "Authorization, Content-Type"
            access-control-max-age: "3600"

spring:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

logging:
    level:
        org.eclipse.jetty: ${LOG_LEVEL_JETTY:WARN}