gnirps:
    core:
        jetty:
            idle-timeout: 300000
        time-zone:
            name: "Europe/Paris"
        mail-sender:
            enable: false
            debug: false
            service-name: "missing-property:gnirps.core.mail-sender.service-name"
            host: ${GNIRPS.CORE.MAIL.SENDER.HOST}
            username: ${GNIRPS.CORE.MAIL.SENDER.USERNAME}
            password: ${GNIRPS.CORE.MAIL.SENDER.PASSWORD}
            recipients: ${GNIRPS.CORE.MAIL.SENDER.RECIPIENTS:nicolas.pittion@redlab.io}
            transport:
                protocol: smtp
            smtp:
                port: 587
                auth: true
                starttls:
                    enable: true
                    required: true

spring:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

logging:
    level:
        org.eclipse.jetty: ${LOG_LEVEL_JETTY:WARN}