gnirps:
    core:
        mail-sender:
            service-name: cat-api-tls
            recipients: ${gnirps.swagger.maintainer.email}
    swagger:
        api:
            title: "Cats-API-TLS"
            description: "Just your average example of API using cats"
            version: 1.2.0-SNAPSHOT
    database:
        hbm2ddl-auto: update