spring:
    profiles: cat

gnirps:
    swagger:
        api:
            title: "Cats-API-TLS"
            description: "Just your average example of API using cats"
            version: 1.2.0-SNAPSHOT
    database:
        hbm2ddl-auto: update

---

spring:
    profiles:
        include: logging, core, swagger, utils, database, postgresql, tls, cat