gnirps:
    core:
        mail-sender:
            service-name: swagger
    swagger:
        base-package: com.gnirps
        api:
            title: ${SWAGGER_TITLE:missing-property:gnirps.swagger.title}
            description: ${SWAGGER_DESCRIPTION:missing-property:gnirps.swagger.description}
            version: ${SWAGGER_VERSION:missing-property:gnirps.common.version}
            license: ${SWAGGER_LICENSE:License:MIT}
            license-url: ${SWAGGER_LICENSE_URL:https://matias.ma/nsfw/}
            terms-of-service: ${SWAGGER_TERMS_OF_SERVICE:https://matias.ma/nsfw/}
            exposed-endpoints: ${SWAGGER_EXPOSED_ENDPOINTS:/**}
        maintainer:
            name: ${SWAGGER_MAINTAINER_NAME:REDLab}
            email: ${SWAGGER_MAINTAINER_EMAIL:nicolas.pittion@redlab.io}
            website: ${SWAGGER_MAINTAINER_WEBSITE:https://www.redlab.io/}
        root-redirect: "swagger-ui.html"
    core:
        mail-sender:
            service-name: cat-api
            recipients: ${gnirps.swagger.maintainer.email}

spring:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
